### Variables here
@url = http://localhost:3010/api/v1/
            
@eventsId = 69f7bd9fc03d11ce71cf6c10
@menuId = 69f7d6aac03d11ce71cf6c23

### GET all events
GET {{url}}events/

### GET full menu
GET {{url}}menu/


### Get events by Id
GET {{url}}events/{{eventsId}}

### GET menu by Id
GET {{url}}menu/{{menuId}}


### POST events
POST {{url}}events/
Content-Type: application/json

{
    "title": "Test Festival",
    "image": "https://Digital-Banners.png",
    "description": "Test Description",
    "dates": "January 1",
    "location": "Lafayette CO",
    "times": "9:00 AM - 5:00 PM"
}

### POST menu
POST {{url}}menu/
Content-Type: application/json

{
     "title": "Grilled Onion Double Cheeseburger",
    "image": "https://www.foodandwine.com/thmb/0SHv4wzGz7OBOcYtVbRWQeuR2CQ=/750x0/filters:no_upscale():max_bytes(150000):strip_icc():format(webp)/MSG-Smash-Burger-FT-RECIPE0124-d9682401f3554ef683e24311abdf342b.jpg",
    "description": "Beef patty x2 with grilled onions, American cheese, pickles, and our special sauce on a toasted bun.",
    "price": "$13.25"
}